### ISSUE TITLE
How to stop proxy process

### ISSUE THREAD

**Issue by manico** [apollographql/apollo-engine-js#100]
Hello, I have terminated my backend koa server using `kill -9` command. Since I did not have yet graceful shutdown, proxy engine is still running. I tried killing it but it just spawns again. What is the procedure to kill process (I see path `node_modules/apollo-engine-binary-linux/engineproxy_linux_amd64 -config=stdin`);

**Comment by manico** [comment]
Ok, I managed to kill it by killing parent node process. Found it using `ps faux`. Any simpler solution for this case?

**Comment by zionts** [comment]
Hi Manico,

Yep, un-graceful shutdowns will tend to leave a bunch of dangling processes. You can certainly accomplish terminating engineproxy via killing the parent node process. When I have a dangling engineproxy process on my dev machine, I generally just kill it using `kill $(ps aux | grep '[e]ngineproxy.*' | awk '{print $2}')` (borrowed from Stack Overflow), but that can definitely be a worrisome route if you have other engineproxies running on your machine that you don't want to kill. 

In the future, I would recommend using `kill -SIGINT` rather than `kill -SIGKILL` unless you need to and making sure that the signal is handled in such a way that will call `engine.stop()` to avoid dangling processes in the future.

**Comment by sunwukonga** [comment]
For anyone else who has the problem of engineproxy not shutting down when the parent is externally terminated other than with `ctrl-c`, I used the following. My specific issue was with supervisord not shutting down engineproxy along with my node process, then dying multiple times (my retry limit) on restart, hence spawning tens of engineproxy at a time. 

npm install signal-exit --save

```
import onExit from 'signal-exit'

const engine = new Engine({ /* your config */ })
function exitHandler(code, signal) {
  this.stop()
}
onExit( exitHandler.bind(engine) )
```

Mischief managed.

`process.on( ... )` didn't work in this situation because it only works on signals generated by node itself, not external signals.
