### ISSUE TITLE
Can bypass blacklist by using alternate content-type.

### ISSUE THREAD

**Issue by thedodd** [apollographql/apollo-engine-js#107]
Using `apollo-server-express@1.3.2` and a standard `apollo-engine@0.8.5` config, blacklisting works just fine when querying the API using `content-type: application/json`. AKA, it will ensure that the `tracing` & `cacheControl` information is not sent back to a user, ever.

However, if you query that same API using `content-type: application/x-www-form-urlencoded`, it will not honor the `Config.Frontend.Extensions.Blacklist` or the `Config.Frontend.Extensions.Strip` configuration, and the user will receive the `tracing` & `cacheControl` information in their response.

**Comment by zionts** [comment]
Hi @thedodd,
What's actually happening here is that Engine Proxy is simply ignoring the query that is being sent and proxying it directly to your origin without reporting it to the Engine cloud service. This is because Engine doesn't support `content-type: application/x-www-form-urlencoded` for GraphQL servers, so it will assume the incoming request is not GraphQL and proxy it to the origin. To resolve this on your end, I would recommend checking the `content-type` header for incoming requests and not serving the response for mismatched content-types. Hope this helps resolve your issue :)

**Comment by thedodd** [comment]
@zionts +1. Thanks for the quick response.
