### ISSUE TITLE
HTTP-verb based endpoint configuration

### ISSUE THREAD

**Issue by joshjcarrier** [apollographql/apollo-engine-js#124]
I serve GraphiQL on GET /graphql but proxying this through Apollo Engine treats this as a GraphQL query. 

Requesting a way to configure an Engine endpoint to only proxy on POST

Relevant documentation: `endpoints` on Config.Frontend https://www.apollographql.com/docs/engine/proto-doc.html#mdg.engine.config.proto.Config.Frontend

**Comment by thepwagner** [comment]
We could do this cheaply in the middleware, but we probably want it in the binary for single-proxy usage?

**Comment by zionts** [comment]
In order to better collect feature requests and bug reports that relate to Apollo Engine Proxy, we have moved this issue (HTTP Verb-based Proxying Rules) into our internal issue tracker, and are correspondingly closing this issue. This is in an effort to collect all customer feedback into the most appropriate place so we can better iterate on the features you want most. For any future feature requests, issues, or questions about **the Apollo Engine Proxy binary**, we urge you to [reach out directly to our team](https://engine.apollographql.com/login?overlay=SupportRequestNoAccount). We appreciate your help in improving Apollo Engine!
