### ISSUE TITLE
Possibility to install only the right apollo-engine-binary?

### ISSUE THREAD

**Issue by ArnaudRinquin** [apollographql/apollo-engine-js#128]
I noticed that my Docker images grew quite a lot since we installed `apollo-engine`.  

It seems that it depends on the 3 `apollo-engine-binary-[darwin|windows|linux]` modules, which are 23Mo each.

While this is not a blocker, shaving off `2* 23Mo` of unnecessary nodes modules would be nice.

I have no clue how to do this though. Any idea?

**Comment by thepwagner** [comment]
Hey @ArnaudRinquin ,
The binary dependencies are all optional: https://github.com/apollographql/apollo-engine-js/blob/master/package.json#L29

So you should be able to```npm install --no-optional apollo-engine apollo-engine-binary-linux``` to get just the linux binary.

**Comment by ArnaudRinquin** [comment]
Perfect! Thanks @thepwagner

**Comment by tejasrsuthar** [comment]
@thepwagner That saved my day! 
Actually, without that `--no-optional` command, I was not able to install apollo-engine at all. 

Thanks for your comment.

**Comment by glasser** [comment]
FWIW, I'd prefer to have the binary packages declare themselves as being a specific OS, so that npm doesn't try to install the wrong-platform ones. However, npm prints big scary warnings when you install platforms that work this way which I think would be intimidating for new users. There has finally been some action on the [npm PR to fix this](https://github.com/npm/npm/pull/19198) so maybe soon this will make sense. (We'll also want to make sure that whatever choice we make is compatible with hosting environments that use `npm rebuild` like Galaxy.)

**Comment by jhalborg** [comment]
+1. I also think this aught to be more explicitly stated in documentation, with an example of how to remove it from production builds as well as best practice for handling it on a dev team.

**Comment by leonaves** [comment]
Why is it done this way? Most platform specific stuff like this is built on install, afaik

**Comment by glasser** [comment]
It is not built on install because it is closed source. But we've learned that shipping a closed source binary proxy isn't actually what our users want, which is why this particular npm module is deprecated.
