### ISSUE TITLE
Response Gzip Compression

### ISSUE THREAD

**Issue by joshjcarrier** [apollographql/apollo-engine-js#149]
When a client sends `Accept-Encoding: gzip, deflate`, feature request that Apollo Engine Proxy can return the HTTP response compressed.

**Comment by zionts** [comment]
In order to better collect feature requests and bug reports that relate to Apollo Engine Proxy, we have moved this issue (Support Response Compression) into our internal issue tracker, and are correspondingly closing this issue. This is in an effort to collect all customer feedback into the most appropriate place so we can better iterate on the features you want most. For any future feature requests, issues, or questions about **the Apollo Engine Proxy binary**, we urge you to [reach out directly to our team](https://engine.apollographql.com/login?overlay=SupportRequestNoAccount). We appreciate your help in improving Apollo Engine!

**Comment by glasser** [comment]
Note that the Proxy should have compression on by default.
