### ISSUE TITLE
apollo-engine doesn't explicitly kill engineproxy on shutdown, which can lead to "port is already in use" errors on restart

### ISSUE THREAD

**Issue by seeden** [apollographql/apollo-engine-js#154]
Hi guys. I have tried your latest version 1.0.1
When I close my node server your apollo engine proxy is still running. And after that I am not able to start my application again. (for example automatically after internal error).
I see message that my port is already in use. And it is because apollo engine proxy is using it.
Anyway how am I able to close your proxy?

**Comment by piehei** [comment]
I'm facing a similar issue when I automatically restart my dev server with nodemon. The port is taken and I have to manually close the whole thing and restart it.

**Comment by sbrichardson** [comment]
I had this issue when testing the upgrade. I was able to resolve it by adding the below to package.json

```json

  "nodemonConfig": {
    "signal": "SIGTERM"
  }


```

**Comment by glasser** [comment]
What's going on here is that ApolloEngine doesn't explicitly try to shut down the engineproxy on Node shutdown. It relies on assuming that whatever caused the Node process to die will also kill engineproxy (eg, CTRL-C SIGINT sent to entire process group, `nodemon` seeking out all subprocesses to kill it, etc).  This works OK in some cases but is flawed in others (eg, server crashing with an uncaught exception).

Before 1.x engineproxy listened on random ports, so this led to a leak (which is bad too) but not a listen failure.

We should change ApolloEngine and ApolloEngineLauncher to set up a variety of event handlers (exit, uncaughtException, SIGINT, SIGTERM, SIGUSR2 [the default for nodemon]) to shut down engineproxy, wait for it to go away (the wait is necessary to make nodemon wait), and re-signal itself to die.  Since this does invade global configuration, you should be able to turn these off or customize the set of signals handled.

This is a priority for me this week.

@sbrichardson I'm a little confused about why setting signal to SIGTERM makes a difference.  engineproxy handles SIGTERM and SIGUSR2 (the default for nodemon) in almost exactly the same way. Maybe your Node process has a SIGTERM handler which takes some time to shut down and so your Node process lasts a bit longer with SIGTERM than with SIGUSR2?

**Comment by sbrichardson** [comment]
I’m not to sure either but adding it fixed it immediately, even if maybe a workaround? If I remove it, I get the port in use error mentioned by others above. I believe I tried SIGUSR etc first but only SIGTERM resolved it. I didn’t investigate further.

**Comment by glasser** [comment]
Better cleanup is released in apollo-engine@1.0.3. Give it a shot and let me know if it works for you!

**Comment by intellix** [comment]
Still getting this every now and again. We're using `ts-node-dev`. Not sure if it changes anything

**Comment by glasser** [comment]
For what it's worth, most of our active development is focused on `apollo-engine-reporting` (built in to `apollo-server` 2.0 and newer) rather than `engineproxy` (ie, `apollo-engine`). All the complexity around spawning a separate proxy process didn't seem worth it in practice.  `engineproxy` is still the only implementation supporting full-query caching and non-Node servers, but we're working on both of those issues.
