### ISSUE TITLE
ApolloEngineLauncher not working inside Zeit's now hosting

### ISSUE THREAD

**Issue by alaister** [apollographql/apollo-engine-js#156]
I am running a seperate proxy server but when I try and load the endpoint, it just keeps loading until I close the tab when the server `http: proxy error: context canceled`.
I am unsure of why this is happening - my code works on my computer but not when deployed.

**Comment by glasser** [comment]
What do you mean by "running a seperate proxy server"?

**Comment by alaister** [comment]
I mean running ApolloEngineLauncher on a seperate instance to my GraphQL sever

**Comment by glasser** [comment]
Can you share the code you use to run ApolloEngineLauncher (including the actual config, eliding passwords / apikey / etc)?

**Comment by alaister** [comment]
Here is my simple index.js file:
const { ApolloEngineLauncher } = require('apollo-engine');

const launcher = new ApolloEngineLauncher({
  apiKey: 'my:api:key',
  origins: [{
    http: {
      url: 'https://graphql.n7.education/graphql',
    },
  }],
  frontends: [{
    port: process.env.PORT || 4000,
  }],
});

launcher.start().catch(err => { throw err; });

See working graphql server here: https://graphql.n7.education/graphql and unresponsive engine here: https://engine.n7.education/graphql

**Comment by glasser** [comment]
When you say "my code works on my computer but not when deployed" does that mean that when you run that file on your computer it does work (through Engine)?  (That's what I'd expect.)

Hmm. Looks like you're using Zeit's now.  I know that it does some special magic where it finds your listen port automatically. Maybe that is failing because the listen is happening in a subprocess?

**Comment by alaister** [comment]
Yep you’re correct my code works when I run it locally but not once deployed.

I am indeed using Now - which is the reason I have them deployed seperatly because of the port detection. So both containers will only be listening on one port instead of it being in one container and Now not knowing which port to use.

**Comment by glasser** [comment]
And there are no errors or anything printed inside Now's interface? I should at least be able to reproduce this with now myself (tomorrow maybe, working on a release right now).

**Comment by alaister** [comment]
The only errors it prints is when you close the tab in when trying to load the engine URL. Which gives you the context cancelled error.
Thanks that would be great!

**Comment by glasser** [comment]
Ah, I see what is going on here. Your graphql.n7.education site is also hosted by Zeit and like most websites is virtually hosted: Zeit needs all incoming requests to have a Host header saying `graphql.n7.education` to properly route to your site.

Engine preserves the original client's Host header (ie, `engine.n7.education`) so that your backend can itself choose to do different things depending on what host the client used to access your app. In the common case where Engine is just redirecting to localhost:12345, this makes a lot of sense, as there isn't any virtual-hosting happening on your localhost. But for a backend hosted on a different virtually-hosted service this doesn't work.

The fix is to just tell Engine to set the host header appropriately:

```
const launcher = new ApolloEngineLauncher({
  apiKey: 'my:api:key',
  origins: [{
    http: {
      url: 'https://graphql.n7.education/graphql',
      overrideRequestHeaders: {
        host: 'graphql.n7.education',
      },
    },
  }],
  frontends: [{
    port: process.env.PORT || 4000,
  }],
});
``` 

Note that Engine will include the original host in an X-Forwarded-Host header if you're still curious to see what it was.

Note that I was able to reproduce something like this issue myself. But (a) when I tried it, I couldn't get it to work locally or on now without the host header and (b) the error I got was an immediate "unknown content-type from origin" issue, not a hang. So it's possible I'm fixing a different issue than the one you're seeing?

Try setting the Host header (and upgrading to 1.0.2 while you're at it), and if that doesn't work, let me know.

**Comment by glasser** [comment]
I added a note to the reference documentation about origin.http.url telling folks they may need to set Host: https://www.apollographql.com/docs/engine/proto-doc.html#Origin-HTTP

**Comment by perminder-klair** [comment]
I am using Koa with ApolloEngine, having same issue. Graphql is working locally, but when i push site live it does not works.
Its hosted on Zeit's now host. its giving tracing details, means its not working. nor sending any data to engine.

Here it is: https://api.luxurylimoland.com/graphiql?query=%7B%0A%20%20allCars%20%7B%0A%20%20%20%20id%0A%20%20%20%20name%0A%20%20%7D%0A%7D

**Comment by glasser** [comment]
@perminder-klair Which API are you using to run engine on Zeit?

As far as I can tell, it's not really possible to use the ApolloEngine API with Zeit's default Node.js setup, because of how it auto-detects the port to forward to. You have two options:

- Use Zeit's Dockerfile setup to run your app as a Docker app instead. You can still have your app be written in Node, use the ApolloEngine API, etc... you just need a little Dockerfile that is built on top of a standard Node base image, adds your files to it, and exposes the port that you tell Engine to listen on.

- Use two separate Zeit deployments, one for your app and one for Engine. The Engine one can be a small Node script using ApolloEngineLauncher, or it can use Zeit's Dockerfile support and use the engine Docker container distribution (the latter may be simpler).  Configure the Engine deployment with your app's deployment as its URL, and *override the Host header*. Configure your DNS to point at your Engine deployment.

**Comment by perminder-klair** [comment]
@glasser I am using `apollo-engine` with `koaApp`.

I just added a Dockerfile and it worked!

```
FROM node:alpine
# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install
# Bundle app source
COPY . /usr/src/app
### RUN npm run start
EXPOSE 4000
CMD [ "npm", "start" ]
```

I am not docker expert, first time done this. Do you think this is correct way?

**Comment by glasser** [comment]
Yep, that sounds roughly right to me! I think you can just move the `copy .` to before the `npm install` and you don't need both that and the package.json line? (You probably want to make sure your package-lock.json is read as part of the npm install)
