### ISSUE TITLE
Port already in use

### ISSUE THREAD

**Issue by khirr** [apollographql/apollo-engine-js#167]
Hello, I have being testing with engine, my problem is when I launch it with "node index.js" it works and start sending reports perfect but when I try to use pm2 (to launch many instances of same file using different cores) it shows port is already in use, it happens using cluster library as well.

When I use express just out of the box for my server, it works perfectly using same port and never problems, just happens when I use engine.listen

Pm2 error: Error: Engine crashed due to invalid configuration. ChildProcess.child.on ...node_modules/apollo-engine/src/launcher.ts:155:13

On cluster show the same error but says "Port already in use".

Thank you.

**Comment by glasser** [comment]
What version of apollo-engine?

**Comment by glasser** [comment]
The ApolloEngine API launches a separate Go binary when you use it. You
don't actually need N copies of that (Go handles concurrency better than
Node) so ApolloEngine is a bad fit for this use case. You may want to just
have pm2 run the underlying binary directly instead. Can give more details
when I'm at my computer tomorrow, or check out this conversation on the
Apollo slack if you're there:
https://apollographql.slack.com/archives/C7FFYGLQG/p1521731891000718

**Comment by khirr** [comment]
Thanks for your reply.

I'm using apollo-engine 1.0.4 but I have test with v0.9.1 (using as middleware), in both cases, same error about port already in use.

In documentation I have ready about using it as a middleware only (v.1.0.4). Is there any document about how to do in my case?

I'm going to join to slack now.

Thanks.

**Comment by glasser** [comment]
The ApolloEngine API runs a proxy binary in front of your Node API. It's intended for basic production (and dev) deploys where you're running one Node server. It's a relatively simple layer on top of the underlying proxy binary that fills in a small number of configuration options for you (the listening interface and the origin URL).

If you're doing something fancier then that, I recommend you just run the binary directly with a fuller configuration, using the ApolloEngineLauncher API in the apollo-engine npm package, or the Docker distribution. Full docs on running the proxy standalone are at https://www.apollographql.com/docs/engine/setup-standalone.html

It's unlikely you actually want to run more than one proxy on a machine --- unlike Node, Go is naturally concurrent and will proxy to N backends just fine.

If you're happy with pm2 you might just want to use it to run the binary directly. If you look at https://github.com/apollographql/apollo-engine-js/blob/master/src/launcher.ts you'll see it's just a thing wrapper around a binary that we ship in submodule apollo-engine-binary-linux (etc). So you can put your config in a json file and ask pm2 to run `node_modules/apollo-engine-binary-linux/engineproxy_linux_amd64 -config x.json`.  Or you can just have pm2 run a very short Node script that uses ApolloEngineLauncher.

If you do this please still install apollo-engine and use the version of the other module pinned by it rather than installing the latest version of apollo-engine-binary-linux directly (which is often some random dev version, it's not meant to be directly installed).

**Comment by tspecht** [comment]
Is there any more straight forward work-around by now?

**Comment by glasser** [comment]
Yes: using apollo-server@2 with apollo-engine-reporting instead of the apollo-engine npm module. We've realized that the complexity of running a separate proxy binary outweighs the advantages of separating Engine support into a separate process and encourage folks to use the simpler new in-process packages.
