### ISSUE TITLE
how to use it with local query

### ISSUE THREAD

**Issue by seeden** [apollographql/apollo-engine-js#32]
I am using local apollo-link. That means I am doing graphql execution directly without any http connection.
How am I able to use this new library?
I wrote something like this in optics:

```js
    const opticsSchema = OpticsAgent.instrumentSchema(schema);
    const isOpticsEnabled = options.apolloEngine && options.apolloEngine.key;

    if (isOpticsEnabled) {
      graphQLContext.opticsContext = OpticsAgent.context(ctx.request);
    }
```

**Comment by joenot443** [comment]
I'm having the same issue using react-apollo. Requests made directly from `/graphiql` show up in Engine, but the ones made from my components using apollo-client don't.

**Comment by zionts** [comment]
Apollo Engine is meant to provide insight into and features that support a GraphQL infrastructure, including a GraphQL server. Because this package wraps around your GraphQL server, if you're doing local state management, Apollo Engine won't be able to track that local information about the error or latency rates since a network call is never made and that data is never attached.

@joenot443 @seeden what are your particular use cases for wanting to see local query analytics in Engine? The one downside that I imagine is that your client will need to make a network call to send the data to Engine (and the latency data will also need to be added via a client-side tracing component), which may defeat the purpose of managing your state locally.

**Comment by seeden** [comment]
I am using it during server side rendering and I want to know which queries or fields are slow.

**Comment by zionts** [comment]
Hi @seeden thanks for letting us know more about your use case. I think this is more a feature request of Apollo-Link-State (or maybe just Apollo Link in general), and I encourage you to [open an issue](https://github.com/apollographql/apollo-link-state/issues/new) there! Because Apollo Engine is meant to provide insight into your GraphQL server, I'm not sure what the path forward would be without one at the moment, but it may mean considering adding support in general to retrieving tracing and cache-control extensions from Apollo Links and enabling Engine for those links? I definitely think it's a conversation worth starting up!
