### ISSUE TITLE
WebSocket support?

### ISSUE THREAD

**Issue by dobesv** [apollographql/apollo-engine-js#33]
Can this be used with websockets?  Based on the source code, it doesn't look like it.

**Comment by zionts** [comment]
In order to better collect feature requests and bug reports that relate to Apollo Engine Proxy, we have moved this issue (Websocket Support) into our internal issue tracker, and are correspondingly closing this issue. This is in an effort to collect all customer feedback into the most appropriate place so we can better iterate on the features you want most. For any future feature requests, issues, or questions about **the Apollo Engine Proxy binary**, we urge you to [reach out directly to our team](https://engine.apollographql.com/login?overlay=SupportRequestNoAccount). We appreciate your help in improving Apollo Engine!
