### ISSUE TITLE
Redis support

### ISSUE THREAD

**Issue by dumbNickname** [apollographql/apollo-engine-js#55]
Are there any plans to support Redis? I was not able to find Apollo Engine code on github so I assume that is is not open sourced (please correct me if I am wrong).

If Redis is not in plans, would it be possible to document what is the format of a request made to memcached and what is the expected response format? (even if some standard memcached API is used, it would be nice to have it linked somewhere in the docs). With such an information it would be easy to expose an endpoint that converts apollo engine request (targeted for memcached) to any other caching/storage engine needed and provide a response that will satisfy the contract for apollo engine. I think it will be easier for people to introduce Engine to their tech stack when they can reuse some existing infrastructure parts (not everybody has memcached or even wants to have it).

**Comment by thepwagner** [comment]
Redis frequently comes up, but hasn't been started yet.

I'll leave this open to aggregate interest and make a case internally, please 👍  for redis!

**Comment by dumbNickname** [comment]
Thanks for a quick response. Additional question - I try to configure external cache as follows:

```
...
"stores": [
      {
        "name": "redisCache",
        "memcache": {
          "url": ["http://127.0.0.1:4000/redisCache"],
          "keyPrefix": "Apollo Engine:"
        }
      }
    ],
    "queryCache": {
      "publicFullQueryStore": "redisCache",
      "privateFullQueryStore": "redisCache"
    },
...
```

Like I wrote above, I will try to expose an endpoint that converts memcached query to redis query to finalize my experiment (as you say Redis needs some time to be approved and added), Unfortunately, my endpoint never gets called. When I use inMemory cache, everything seems to work. The error that I see in Engine debug logs is:
```
EngineProxy ==> time="2017-11-23T15:25:33+01:00" level=warning msg="Query not stored to query cache." error="error saving response to query cache: dial unix http://127.0.0.1:4000/redisCache: socket: An address incompatible with the requested protocol was used."
```
As Engine is being run as .exe (in my case Windows) I do not really know if it is a configuration issue or such a loop back connection to localhost is not allowed by design. Any hints would be appreciated :)

**Comment by pcarrier** [comment]
memcached uses its own protocol which isn't HTTP. You can find docs @ https://github.com/memcached/memcached/blob/master/doc/protocol.txt
We use https://github.com/bradfitz/gomemcache as a client and pass the URLs straight to it.
Then Engine uses PUT, GET and MULTI, though this might change over time.
From the error it looks like gomemcache is trying to create a Unix socket, probably because `http://127.0.0.1:4000/redisCache` looks more like a path to it (like `/tmp/mysql.sock`) than an IP and port (like `127.0.0.1:11211`).

Please note that if you can get started with engineproxy's in-memory cache if you do not want to introduce memcached to get started, but at this stage we only support memcached as a shared cache.

**Comment by mxstbr** [comment]
I'd love Redis support since we already have a couple Redis instances running :blush:

**Comment by zionts** [comment]
In order to better collect feature requests and bug reports that relate to Apollo Engine Proxy, we have moved this issue (Redis Support for Caching) into our internal issue tracker, and are correspondingly closing this issue. This is in an effort to collect all customer feedback into the most appropriate place so we can better iterate on the features you want most. For any future feature requests, issues, or questions about **the Apollo Engine Proxy binary**, we urge you to [reach out directly to our team](https://engine.apollographql.com/login?overlay=SupportRequestNoAccount). We appreciate your help in improving Apollo Engine!

**Comment by ojongerius** [comment]
@zionts any indication if works has started on this, and when this will be supported?

**Comment by krisread** [comment]
Redis is pretty popular, and widely available, we need this!

**Comment by zionts** [comment]
@ojongerius we are currently working on a plan to open source the in-query functionality of Engine, which will include a more pluggable interface for caching support :)

**Comment by tiefenb** [comment]
Yes, Redis please. and memcached SASL
