### ISSUE TITLE
Cannot unmarshal object into Go struct field SerializedQuery.query of type string

### ISSUE THREAD

**Issue by kamal** [apollographql/apollo-engine-js#80]
The proxy is throwing the error `error decoding JSON: json: cannot unmarshal object into Go struct field SerializedQuery.query of type string`.

Debug logs from the proxy

```
{ proxy: 
   { level: 'debug',
     msg: 'reporting-client - [DEBUG] POST https://engine-report.apollodata.com/api/ss/stats',
     time: '2017-12-19T17:28:40-08:00' } }
{ proxy: 
   { level: 'debug',
     msg: 'reporting-client - [DEBUG] POST https://engine-report.apollodata.com/api/ss/stats',
     time: '2017-12-19T17:28:45-08:00' } }
{"query":{"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"UpdateInSessionDeliveriesQuery"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"id"}},"type":{"kind":"NonNullType","type":{"kind":"ListType","type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}}}}],"directives":[],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"deliveries"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"id"}}}],"directives":[],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"InSessionDeliveryFragment"},"directives":[]}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"InSessionDeliveryFragment"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Delivery"}},"directives":[],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"__typename"},"arguments":[],"directives":[]},{"kind":"Field","name":{"kind":"Name","value":"id"},"arguments":[],"directives":[]},{"kind":"Field","name":{"kind":"Name","value":"imageFull"},"arguments":[],"directives":[],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"__typename"},"arguments":[],"directives":[]},{"kind":"Field","name":{"kind":"Name","value":"uri"},"arguments":[],"directives":[]}]}},{"kind":"Field","name":{"kind":"Name","value":"status"},"arguments":[],"directives":[]},{"kind":"Field","name":{"kind":"Name","value":"receivedAt"},"arguments":[],"directives":[]},{"kind":"Field","name":{"kind":"Name","value":"recipient"},"arguments":[],"directives":[],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"__typename"},"arguments":[],"directives":[]},{"kind":"Field","name":{"kind":"Name","value":"id"},"arguments":[],"directives":[]},{"kind":"Field","alias":{"kind":"Name","value":"name"},"name":{"kind":"Name","value":"formattedName"},"arguments":[],"directives":[]}]}},{"kind":"Field","name":{"kind":"Name","value":"carrier"},"arguments":[],"directives":[],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"__typename"},"arguments":[],"directives":[]},{"kind":"Field","name":{"kind":"Name","value":"id"},"arguments":[],"directives":[]},{"kind":"Field","name":{"kind":"Name","value":"name"},"arguments":[],"directives":[]}]}},{"kind":"Field","name":{"kind":"Name","value":"deliveryArea"},"arguments":[],"directives":[],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"__typename"},"arguments":[],"directives":[]},{"kind":"Field","name":{"kind":"Name","value":"id"},"arguments":[],"directives":[]},{"kind":"Field","name":{"kind":"Name","value":"name"},"arguments":[],"directives":[]}]}}]}}],"loc":{"start":0,"end":162,"source":{"body":"#import \"./inSessionDeliveryFragment.graphql\"\n\nquery UpdateInSessionDeliveriesQuery($id: [ID!]!) {\n  deliveries(id: $id) {\n    ...InSessionDeliveryFragment\n  }\n}\n","name":"GraphQL request","locationOffset":{"line":1,"column":1}}}},"operationName":"UpdateInSessionDeliveriesQuery","variables":{"id":["6db6b2b0-4866-49d7-8f3d-38a617becf08"]}}{ proxy: 
   { code: 400,
     error: 'error decoding JSON: json: cannot unmarshal object into Go struct field SerializedQuery.query of type string',
     level: 'warning',
     message: 'The query failed!',
     msg: 'Query error',
     time: '2017-12-19T17:28:45-08:00' } }
{ proxy: 
   { level: 'debug',
     msg: 'Updated StatsState',
     time: '2017-12-19T17:28:45-08:00' } }
{"errors":[{"message":"Internal error"}]}
```

Worth noting that this request was crafted via `Rx.Observable.ajax` instead of the graphql HOC or ApolloClient

```typescript
      return Rx.Observable.ajax({
        url: config.graphQLEndpoint,
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`
        },
        body: {
          query: UpdateInSessionDeliveriesQuery,
          operationName: 'UpdateInSessionDeliveriesQuery',
          variables: { id }
        }
      })
```

`UpdateInSessionDeliveriesQuery` itself is fairly simple

```graphql
#import "./inSessionDeliveryFragment.graphql"

query UpdateInSessionDeliveriesQuery($id: [ID!]!) {
  deliveries(id: $id) {
    ...InSessionDeliveryFragment
  }
}
```

and `InSessionDeliveryFragment`

```graphql
fragment InSessionDeliveryFragment on Delivery {
  __typename
  id
  imageFull {
    __typename
    uri
  }
  status
  receivedAt
  recipient {
    __typename
    id
    name: formattedName
  }
  carrier {
    __typename
    id
    name
  }
  deliveryArea {
    __typename
    id
    name
  }
}
```

I can confirm this works as expected when I disable Engine.

**Comment by zionts** [comment]
Hi @kamal thanks for bringing this to us. I'm happy to help dig into this to figure out what's going on. As a first question, are you using batched queries or single queries? There are two different paths that would cause you to hit that error (one being batched and one individual), and if you're using one but specifying the other, that could definitely cause the issue. I don't think it should make a difference that you're using Rx.observable.ajax as long as the JSON is valid. Another question is what version of EngineProxy are you using? You can figure that out by running `node_modules/apollo-engine-binary-darwin/engineproxy_darwin_amd64 -version`.

**Comment by kamal** [comment]
Version: `engine-proxy 2017.12-28-gcc16cbea7`. This is a single query.

**Comment by kamal** [comment]
I've updated to 0.8.1 with proxy version `engine-proxy 2017.12-45-g12ba029f9` and it still has this issue.

**Comment by glasser** [comment]
Are you able to see (eg, by looking in the network tab of your browser's dev tools) what the posted query from your client looks like?

My suspicion is that your client is posting (in the "query" field) a JSON object that is a parse tree of a GraphQL query (ie, the thing starting with `{"kind":"Document","definitions":`) rather than a string in the GraphQL language.

**Comment by kamal** [comment]
@glasser yes it is posting the AST as I'm using babel-plugin-inline-import-graphql-ast. My understanding is that that's what the gql tag does as well except that this does it at compile time. As mentioned, this set up works perfectly with apollo-server express middleware and only an issue with the engine proxy.

**Comment by pcarrier** [comment]
We don't currently support `JSON.stringify`'ed graphql-js AST as this format is not standardized (or even documented AFAICT). I have yet to see an argument for transporting it over the network (particularly given it's bigger than the original and seemingly not faster to parse). Could you please let us what your use case is, and why it makes more sense than the GraphQL format there?

**Comment by billxinli** [comment]
I am seeing similar errors over here as well.

I am getting:
```
{
  "errors": [
    {
      "message": "Error decoding JSON response from origin"
    }
  ]
}
```

From the Introspection query from Graphiql

**Comment by zionts** [comment]
@billxinli This likely means that your GraphQL server is not returning valid JSON as @pcarrier indicated above, and so Engine runs into an error attempting to decode the response from the origin. Do you know what raw responses look like coming from your origin? I also highly recommend opening a [support ticket](engine.apollographql.com/support) so we can better assist – we're here to help!

**Comment by brandonmp** [comment]
Piling on. This error presents only when Engine is active (which made it hard to trace!)

```
{ proxy: 
   { code: 400,
     error: 'error decoding JSON: json: cannot unmarshal object into Go struct field SerializedQuery.query of type string',
     level: 'warning',
     message: 'The query failed!',
     msg: 'Query error',
     time: '2018-04-03T19:07:23Z' } }
```

Query is from client-side `graphql-request`

**Comment by glasser** [comment]
This one is different — as you suggest, it's from a non-JSON *request* not response.  It looks like you are passing a non-string as the `query`.  If you use graphql-request, it looks like they expect query to be a string (as do we) though I guess they don't actually validate that? https://github.com/graphcool/graphql-request/blob/master/src/index.ts

**Comment by brandonmp** [comment]
Ah, great catch, thanks--yeah, I'm passing a `graphql-tag`, and `graphql-request` isn't confirming it's a string.

`apollo-server` accepts the mutation fine, though, if `apollo-engine` isn't configured. Is it that `apollo-server` _prefers_ a string, but will accept a `graphql-tag`?

**Comment by glasser** [comment]
As described above, the thing you are doing is not GraphQL.  GraphQL is a language with a spec. The thing you are passing is a JSON rendering of the parsed AST from a particular implementation. I guess it is sort of neat that there exist pairs of clients and servers that coincidentally manage to successfully communicate using this random intermediate representation format, but it's not GraphQL and it's not a bug that other GraphQL implementations don't support it.  As I mentioned, if you were using your client (`graphql-request`) with TypeScript (its implementation language) your code wouldn't compile because it expects to receive queries as strings.

**Comment by brandonmp** [comment]
> As I mentioned, if you were using your client (graphql-request) with TypeScript (its implementation language) your code wouldn't compile because it expects to receive queries as strings.

haha, turns out, I _am_ using typescript. it looks like[ `graphql-tag` is typed to return `any`.](https://github.com/apollographql/graphql-tag/blob/master/index.d.ts) 

I'm still new to TypeScript, but I think that might be why I was able to pass a `graphql-tag` instead of a `string`.

**Comment by javierfernandes** [comment]
Hi guys, I'm also getting this issue. My scenario is that I'm using apollo-client + apollo-server, and the frontend uses webpack `graphql-tag/loader` to be able to import queries and pass them to the client.
Now, for a particular query I'm using `graphql-client` to do the fetching. And I'm passing the query as it comes from importing it.
That works fine if the backend is not using `apollo-engine`. But if I enable it, it fails with

```
WARN[1151] Query error                                   code=400 error="error decoding JSON. This likely means that the GraphQL request was malformatted.: json: cannot unmarshal object into Go struct field SerializedQuery.query of type string" message="The query failed."
```

Here is a sample code just to give you an idea

```js
import query from 'api/queries/objects.graphql'
import clientFactory from 'graphql-client'
...
const client = clientFactory({ url })
const objects = await client.query(query, { projectName: project })
```

The question is, how should I be passing the query ? Is there a way to convert the parsed AST back to text ?? I understand that would be just a workaround because it makes no sense to parse it (webpack) just to later get back the original text. So then do you think that the solution would be to exclude this particular query from webpack's graphql-tag/loader and instead load it inlined as a string ?

Lastly, just as feedback, it is a little bit confusing that `apollo-server` can handle this while `apollo-engine` don't. It would be great if they both are idempotent :P  Moreover if the idea is that one just hooks apollo-engine as a transparent proxy. 

Thanks !!

**Comment by glasser** [comment]
Right, I'm not very familiar with `graphql-client` but its docs suggest that it intends to get passed a string for the query rather than a `graphql-tag` object.  I suggest using `apollo-client` or `apollo-link`, or if you really want to use `graphql-client` with `graphql-tag`, use the printer from `graphql` to convert the internal Node AST representation to real GraphQL.

I recognize that it's confusing that apollo-server accidentally supports passing the AST on the network. @jbaxleyiii is working on apollo-server 2.0 right now and I believe we're planning to remove this bug from apollo-server.  I think it's as simple as changing runHttpQuery to make sure the query is actually a query (string).  (I wish I knew what the comment `This refers the operations-store flow` in runQuery meant, but if we do the change in runHttpQuery instead we can ignore that.)

**Comment by glasser** [comment]
Oh, to be specific what you're looking for is `import { print } from 'graphql'; print(queryAST)` but again, I'd recommend using one of the apollo clients (if you're looking for something very simple, `apollo-link-http` is basically as simple as `graphql-client`).

**Comment by javierfernandes** [comment]
@glasser that all seems cool.
I will see if we can use apollo-link or some more "low-level" API for this case (I just need like the transport without cache, I will handle that part myself with redux :P)

And glad to hear that you are working on a solution to make apollo-server consistent.

Thanks !!!

**Comment by elie222** [comment]
For others running into this using `graphql-request` with Apollo Server 2, don't use `graphql-tag`. Just use a string.

It worked fine with Apollo Server 1, but won't with version 2.
