### ISSUE TITLE
Using compress middleware is crashing engine proxy

### ISSUE THREAD

**Issue by renatobenks** [apollographql/apollo-engine-js#96]
Hey there, when I'm using the compress middleware from `koa-compress` in my koa graphql server, the server crashes, because the proxy by apollo engine not connect with my localhost.

Of course, when the `compress` middleware is enabled, the server crashes, and is not, the server works fine.

For now, I'm with my `koa-compress` disabled, to enable apollo engine works well, but, I think this issue, it's so much important. Because, the own setup for apollo-engine with node (https://www.apollographql.com/docs/engine/setup-node.html), it's indicating to enable the `compress` middleware. So this way, potentially, everyone that will gonna try setup this, in a koa server, will gonna go crashes server too, as well, has the same issue.

_I followed the nodejs setup for koa, and nothing more._

**version:** ^0.8.4

Probably it's related with #54. Thanks a lot!

**Comment by renatobenks** [comment]
@stubailo please, help with this one!

**Comment by zionts** [comment]
Hi there,
Thanks for reaching out about this! I'll start off by saying that the best place to get support for this is through [Apollo Engine support](engine.apollographql.com/support). That said, I'm happy to help you figure out what's going on. One of the most common problems that we encounter is when people have middlewares before the engine middleware. Because it is proxying traffic, it's important that the engine middleware is set up before the compression middleware. You're definitely right that it's not very clear that we expect the `engine.koaMiddleware()` call to be before the compression, and I'll take a look into how we can make that more clear. When you change the ordering of the middlewares to ensure that Engine's is the first, do you still have the same problem?

**Comment by renatobenks** [comment]
@zionts thank you so much! Your helpful was so util, really thanks.

It's working very well now, with `compress` middleware before `engine.koaMiddleware()`.

Therefore, this explanation should be on setup docs with this details, commenting about this.
